name: Deploy Angular 20 + Tailwind CSS to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install Dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular App
      - name: Build Angular App
        run: npm run build --if-present

      # 5️⃣ Deploy to Vercel
      # - name: Deploy to Vercel
      #   run: |
      #     npm install -g vercel@latest
      #     vercel --prod --token=$VERCEL_TOKEN --confirm --cwd ./dist/my-app
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
